# Introducción a Julia y Jupyter-notebook

El texto canónico es el [manual de Julia](https://docs.julialang.org/en/v1/)

[Julia](http://julialang.org/) es un lenguaje concebido para hacer cómputo científico, y por gente que tiene experiencia en eso. Incorpora muchos elementos modernos del diseño de lenguajes de cómputo.

Por ejemplo, cosas como "pi" y kron (producto de kronecker) están definidas.

Uso de Jupyter-notebook
============================

Jupyter es una herramienta muy util para desarrollar código de Julia y Python, entre muchos otros lenguajes. Tiene elementos que recuerdan los notebooks de Mathematica.

Modo Esc:
----------------------

* Presionando "a"/"b" abre una celda arriba arriba/abajo __above/bottom__ de la que actualmente esta seleccionada.

* presionando "d" dos veces se borra la celda seleccionada.

* "m" cambia la celda a Markdown

Presionando Enter se cambia al modo de edición de celda
------------------------------------------------------------

* Las celdas se evaluan con "shift+Enter" (como en mathematica, solo que aqui no funciona el Intro)

* Las celdas aceptan diversos lenguajes tales como `MarkDown`, el mismo lenguaje en el que fue escrita esta celda.

* El notebook permite varios modos interesantes, por ej. presionando ctrl y haciendo click con el mouse en diferentes partes del codigo, el notebook nos brinda muchos cursores.




## Instalacion y uso de paqueterias de Julia

* El comando Pkg.update() actualiza la información de los repositorios de Julia
* Pkg.add("Nombre del paquete") instala el paquete deseado, por ejemplo, si queremos instalar PyPlot para poder hacer graficas:
* __Nota:__ La primera vez que el kernel de Julia se ejecuta en un nuevo note

In [2]:
using Pkg
Pkg.update()
Pkg.add("PyPlot")

    Updating registry at `~/.julia/registries/General.toml`
   Installed libpng_jll ─ v1.6.46+0
  No Changes to `~/.julia/environments/v1.11/Project.toml`
    Updating `~/.julia/environments/v1.11/Manifest.toml`
  [b53b4c65] ↑ libpng_jll v1.6.45+1 ⇒ v1.6.46+0
Precompiling project...
   1091.5 ms  ✓ libpng_jll
   1094.2 ms  ✓ Cairo_jll
    776.5 ms  ✓ HarfBuzz_jll
    889.8 ms  ✓ Pango_jll
    939.8 ms  ✓ libass_jll
   1143.0 ms  ✓ libdecor_jll
   1419.2 ms  ✓ FFMPEG_jll
   1196.7 ms  ✓ GLFW_jll
   1145.6 ms  ✓ FFMPEG
   1334.6 ms  ✓ GR_jll
   5448.6 ms  ✓ GR
  74923.7 ms  ✓ Plots
   3978.1 ms  ✓ Plots → UnitfulExt
  13 dependencies successfully precompiled in 94 seconds. 180 already precompiled.
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.11/Project.toml`
  No Changes to `~/.julia/environments/v1.11/Manifest.toml`


# Lo básico

Originalmente las funciones especiales estaban precargadas en el kernel de Julia, sin embargo, luego de el lanzamiento de la versión 1 de Julia, este ya no es el caso. Como por ejemplo la función $J_0$ de Bessel:

Antes de intentar ejecutar las funciones, importemos el paquete necesario. Es importante observar que al trabajar en un notebook, los paquetes y variables que carguemos son globales en todo el notebook.

In [3]:
# Importamos la librería con funciones especiales
Pkg.add("SpecialFunctions") # Esto solo es necesario la primera vez, por supuesto.
using SpecialFunctions

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.11/Project.toml`
  No Changes to `~/.julia/environments/v1.11/Manifest.toml`


In [4]:
besselj0(pi/4)

0.8516319137048081

In [5]:
zeta(1.1) # Zeta de Riemann

10.584448464950801

In [6]:
@doc zeta # Para pedir ayuda

```
zeta(s, z)
```

Generalized zeta function defined by

$$
\zeta(s, z) = \sum_{k=0}^\infty \frac{1}{((k+z)^2)^{s/2}},
$$

where any term with $k+z = 0$ is excluded.  For $\Re z > 0$, this definition is equivalent to the Hurwitz zeta function $\sum_{k=0}^\infty (k+z)^{-s}$.

The Riemann zeta function is recovered as $\zeta(s) = \zeta(s,1)$.

External links: [Riemann zeta function](https://en.wikipedia.org/wiki/Riemann_zeta_function), [Hurwitz zeta function](https://en.wikipedia.org/wiki/Hurwitz_zeta_function)

```
zeta(s)
```

Riemann zeta function

$$
\zeta(s) = \sum_{n=1}^\infty \frac{1}{n^s}\quad\text{for}\quad s\in\mathbb{C}.
$$

External links: [Wikipedia](https://en.wikipedia.org/wiki/Riemann_zeta_function)


In [7]:
pi

π = 3.1415926535897...

__Nota:__

In [8]:
π # se genera excribiendo `\pi<TAB>`

π = 3.1415926535897...

In [9]:
1/2

0.5

In [10]:
1/2==0.5

true

In [11]:
typeof(1/2)

Float64

Julia admite racionales:

In [12]:
1//2+1//3

5//6

In [13]:
typeof(1//2)

Rational{Int64}

In [14]:
1//2==0.5

true

### Números complejos

In [15]:
1+im

1 + 1im

In [16]:
typeof(ans)

Nothing

In [17]:
0.1+im

0.1 + 1.0im

In [18]:
typeof(ans)

Nothing

In [19]:
π*im

0.0 + 3.141592653589793im

In [20]:
typeof(ans)

Nothing

Julia también soporta números irracionales (está equipado con el tipo Irrational)

In [21]:
exp(1)

2.718281828459045

In [22]:
ℯ

ℯ = 2.7182818284590...

In [23]:
typeof(π), typeof(ℯ)

(Irrational{:π}, Irrational{:ℯ})

### Definición de variables

In [24]:
x=π # se hace de la manera usual

π = 3.1415926535897...

In [25]:
x

π = 3.1415926535897...

In [26]:
2x

6.283185307179586

## Copiado de variables

Observar con cuidado lo siguiente:

In [27]:
x = 2

2

In [28]:
a = x

2

In [29]:
x = 3

3

In [30]:
a

2

In [31]:
# Shallow copy example
original_array = [[1, 2, 3], [4, 5, 6]]
shallow_copy = copy(original_array)

println("Original array: ", original_array)
println("Shallow copy: ", shallow_copy)

# Modify the deep copy
original_array[1][1] = 10

println("After modifying the original:")
println("Original array: ", original_array)
println("Shallow copy: ", shallow_copy)

Original array: [[1, 2, 3], [4, 5, 6]]
Shallow copy: [[1, 2, 3], [4, 5, 6]]
After modifying the original:
Original array: [[10, 2, 3], [4, 5, 6]]
Shallow copy: [[10, 2, 3], [4, 5, 6]]


In [32]:
# Deep copy example
original_array = [[1, 2, 3], [4, 5, 6]]
deep_copy = deepcopy(original_array)

println("Original array: ", original_array)
println("Deep copy: ", deep_copy)

# Modify the deep copy
original_array[1][1] = 10

println("After modifying the original:")
println("Original array: ", original_array)
println("Deep copy: ", deep_copy)

Original array: [[1, 2, 3], [4, 5, 6]]
Deep copy: [[1, 2, 3], [4, 5, 6]]
After modifying the original:
Original array: [[10, 2, 3], [4, 5, 6]]
Deep copy: [[1, 2, 3], [4, 5, 6]]


deepcopy es recursivo, pero no así copy. Que pasa con arreglos de una dimensión? (Ejercicio)

## Precisión extendida

In [33]:
BigFloat("3.14")

3.140000000000000000000000000000000000000000000000000000000000000000000000000008

In [34]:
a = BigFloat("2.0001")

2.0001

In [35]:
typeof(a)

BigFloat

# Precisión de la maquina y números representables

In [36]:
# Machine precision for Float64
eps_float64 = eps(Float64)
# Smallest representable number for Float64
min_float64 = floatmin(Float64)
# Largest representable number for Float64
max_float64 = floatmax(Float64)

# Machine precision for BigFloat
eps_bigfloat = eps(BigFloat)
# Smallest representable number for BigFloat
min_bigfloat = floatmin(BigFloat)
# Largest representable number for BigFloat
max_bigfloat = floatmax(BigFloat)

# Print the results
println("Float64:")
println("Machine precision: ", eps_float64)
println("Smallest representable number: ", min_float64)
println("Largest representable number: ", max_float64)

println("\nBigFloat:")
println("Machine precision: ", eps_bigfloat)
println("Smallest representable number: ", min_bigfloat)
println("Largest representable number: ", max_bigfloat)

Float64:
Machine precision: 2.220446049250313e-16
Smallest representable number: 2.2250738585072014e-308
Largest representable number: 1.7976931348623157e308

BigFloat:
Machine precision: 1.727233711018888925077270372560079914223200072887256277004740694033718360632485e-77
Smallest representable number: 8.50969131174083613912978790962048280567755996982969624908264897850135431080301e-1388255822130839284
Largest representable number: 5.875653789111587590936911998878442589938516392745498308333779606469323584389875e+1388255822130839282


# Vectores, matrices y otras estructuras

In [37]:
a = [3, 2.0, 1.0]

3-element Vector{Float64}:
 3.0
 2.0
 1.0

In [38]:
typeof(a)

Vector{Float64} (alias for Array{Float64, 1})

In [39]:
a = ["foo", "bar", 10]

3-element Vector{Any}:
   "foo"
   "bar"
 10

In [40]:
typeof(a)

Vector{Any} (alias for Array{Any, 1})

In [41]:
zeros(10)

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

Matriz en ceros

In [42]:
ze=zeros(2,3)

2×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0

Creando vectores en ceros especificando el tipo.

In [43]:
zeros(Int8,10)

10-element Vector{Int8}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [44]:
using LinearAlgebra

In [45]:
@doc LinearAlgebra

Linear algebra module. Provides array arithmetic, matrix factorizations and other linear algebra related functionality.


In [46]:
I

UniformScaling{Bool}
true*I

In [47]:
2*I

UniformScaling{Int64}
2*I

In [48]:
id = Matrix{Float64}(I, 2, 2)

2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0

In [49]:
id[1,2]

0.0

In [50]:
id[1,1]

1.0

In [51]:
id[1]

1.0

In [52]:
id[4]

1.0

Julia comienza a contar desde el 1, cosa que es poco usual en los lenguajes de programación comunes.

Otra forma de crear matrices:

In [53]:
[1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

Covectores:

In [54]:
co = [1 2 3 4]

1×4 Matrix{Int64}:
 1  2  3  4

vectores

In [55]:
transpose(co)

4×1 transpose(::Matrix{Int64}) with eltype Int64:
 1
 2
 3
 4

In [56]:
typeof(co)

Matrix{Int64} (alias for Array{Int64, 2})

In [57]:
Matrix(1I, 3, 3)    # Identity matrix of Int type
Matrix(1.0I, 3, 3)  # Identity matrix of Float64 type
Matrix(I, 3, 3)     # Identity matrix of Bool type

3×3 Matrix{Bool}:
 1  0  0
 0  1  0
 0  0  1

In [58]:
Matrix{Int}(I, 3, 3)      # Identity matrix of Int type
Matrix{Float64}(I, 3, 3)  # Identity matrix of Float64 type
Matrix{Bool}(I, 3, 3)     # Identity matrix of Bool type

3×3 Matrix{Bool}:
 1  0  0
 0  1  0
 0  0  1

__Creación de vectores en blanco__

Si queremos por ejemplo un vector de enteros sin especificar las entradas, pero con dimensión fija, podemos hacer:

In [59]:
array = Array{Int64}(undef, 5)

5-element Vector{Int64}:
 13510798882111488
   135780316410704
   135780235232848
   135780960482320
   135780958960944

In [60]:
array = Array{Int64}(undef, 5,6)

5×6 Matrix{Int64}:
 135780918273376  135780918273376  …  135780918273376  135780918273376
 135780918273376  135780918273376     135780918273376  135780918273376
 135780918273376  135780918273376     135780918273376  135780918273376
 135780918273376  135780918273376     135780918273376  135780918273376
 135780918273376  135780918273376     135780918273376  135780918273376

In [61]:
z= Array{Vector{Float64}}(undef, 10, 100)

10×100 Matrix{Vector{Float64}}:
 #undef  #undef  #undef  #undef  #undef  …  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef  …  #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef
 #undef  #undef  #undef  #undef  #undef     #undef  #undef  #undef  #undef

In [62]:
z= Array{Float64}(undef, 10, 100)

10×100 Matrix{Float64}:
 0.0             8.70018e-313  …    0.0           NaN
 0.0             8.48798e-314       0.0             1.07625e247
 4.81788e-316  NaN                  2.88218e-316    5.234e245
 6.70848e-310    5.28163e-315       9.72767e-315   -1.05577e201
 5.28163e-315    0.0              NaN               2.90536e-316
 5.28163e-315    5.28911e-315  …    6.54764e-292    8.34335e-292
 4.24399e-314    5.34689e-315       8.79779e-318  NaN
 5.30754e-315    5.28163e-315       1.37131e-289  NaN
 5.28163e-315    1.6976e-313      NaN               0.0
 5.26458e-315    6.70848e-310       4.83595e86     -8.9298e82

# Esturcturas basicas

## bucles y expresiones condicionales

In [63]:
# for simple
for i in -1:3
    println(i)
end

-1
0
1
2
3


In [64]:
typeof(-1:3)

UnitRange{Int64}

In [65]:
i # i es una variable local

UndefVarError: UndefVarError: `i` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [66]:
for i in 1:3
    r = i
    println(r)
end

1
2
3


In [67]:
r # esta es local también, esta dentro del for

UndefVarError: UndefVarError: `r` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [68]:
r = 0
for i in 1:2:10
    r = i
    println(r)
end

1
3
5
7
9


In [69]:
r #Aqui ya no es local, está definida como global, pues se definió fuera del bucle.

9

In [70]:
for ib = (true, false)
    for jb = (true,false)
        println( "$ib & $jb = ", ib & jb)
        println( "$ib | $jb = ", ib | jb)
    end
end

true & true = true
true | true = true
true & false = false
true | false = true
false & true = false
false | true = true
false & false = false
false | false = false


* While

In [71]:
i=0;
while i <= 5
         println(i)
         i += 1
end

0
1
2
3
4
5


* If

In [72]:
y=5;
x=6;
if x < y
  println("x is less than y")
elseif x > y
  println("x is greater than y")
else
  println("x is equal to y")
end

x is greater than y


## Creacion de funciones

In [73]:
# Calculo del volumen de una esfera de radio r
function sphere_vol(r)
    return 4/3*pi*r^3
end

sphere_vol (generic function with 1 method)

In [74]:
typeof(sphere_vol)

typeof(sphere_vol) (singleton type of function sphere_vol, subtype of Function)

In [75]:
sphere_vol(1)

4.1887902047863905

### Ejemplo : Método de Newton para calcular raices cuadradas (Método Babilónico)

* Para calcular la raiz cuadrada de $S$ un método bastante conocido es el de los Babilonios (derivable del método de newton para buscar ceros). El algoritmo puede ser presentado como un sistema dinámico discreto:
$$x_{n+1}=\frac{1}{2} \left( x_n+\frac{S}{x_n} \right), \hspace{5 pt} \lim_{n\to\infty} x_n\to \sqrt{S}.$$
Donde $x_0$ es una condicion inicial cualquiera, finita y acotada. Típicamente uno escoge una buena condicion inicial para que el metodo converja rapido.

__Nota:__ Por favor entiendan que para encontrar la fórmula anterior solo se sustituyó: 
$$f(x)=x^2-S \hspace{10 pt} \text{y} \hspace{10 pt} f'(x)=2x.$$

In [76]:
"""
Esta función calcula la raiz cuadrada
"""
function sqrt_root(S)
    x=S/2;
    for i in 1:20
       x=0.5(x+S/x)
    end
    return x
end

sqrt_root

In [77]:
sqrt_root(2)

1.414213562373095

In [78]:
sqrt(2)

1.4142135623730951

* Podemos mirar la documentación que agregamos a nuestra función como cualquier otra función de Julia:

In [79]:
?sqrt_root

Base.Meta.ParseError: ParseError:
# Error @ /home/david/Dropbox/postdoc_gorin/clases/metodos/metodos_sim_num/clases/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y344sZmlsZQ==.jl:1:1
?sqrt_root
╙ ── not a unary operator

__Ejercicio 1:__ Crear una rutina que calcule las raices de la siguiente ecuación trascendental: 
$$x \tan(x)=\sqrt{A-x^2},$$
esta ecuación tiene interes en la física cuántica de particulas en una dimensión, en particular, sus soluciones estan directamente relacionadas con las eigenenergias del _pozo finito cuadrado_, y el número de soluciones posibles es precisamente el número de estados _ligados_ que caben en el pozo.

__Nota:__ Usar varias condiciones iniciales $x_0$.